services:
  client:
    build: ./client
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
    environment:
      - VITE_API_URL=http://localhost:3000
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client/package.json
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    environment:
      - DATABASE_URL=mongodb://mongo:27017/prm-freelance-db
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./server/package.json
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
networks:
  app-network:
    driver: bridge